export const PET_STATUSES = ["Perdido", "Encontrado", "Reunido"];
export const PET_SIZES = ["Pequeño", "Mediano", "Grande"];
export const PET_SEXES = ["Macho", "Hembra", "No se sabe"];
export const ZONES = ["Equipetrol", "Urubó", "Las Palmas del Norte", "El Norte"];

export const DEMO_PETS = [
  {
    id: "demo-rocco",
    name: "Rocco",
    photo: "./assets/dogs/rocco.jpg",
    status: "Perdido",
    reportDate: "2026-08-24",
    eventDate: "2026-08-23",
    zone: "Equipetrol",
    location: "Parque de Equipetrol, cerca de la avenida San Martín",
    breed: "Golden Retriever",
    size: "Grande",
    sex: "Macho",
    age: "4 años",
    color: "Dorado",
    marks: "Collar azul y una pequeña mancha blanca en el pecho",
    description:
      "Rocco salió por el portón durante la tarde. Es amistoso, responde a su nombre y puede asustarse con motocicletas o bocinas fuertes.",
    contactName: "Familia Rivera",
    phone: "+591 70000001",
    email: "",
    isUserCreated: false,
  },
  {
    id: "demo-luna",
    name: "Luna",
    photo: "./assets/dogs/luna.jpg",
    status: "Perdido",
    reportDate: "2026-08-25",
    eventDate: "2026-08-25",
    zone: "El Norte",
    location: "Avenida Banzer, altura del séptimo anillo",
    breed: "Mestiza",
    size: "Mediano",
    sex: "Hembra",
    age: "3 años",
    color: "Negro, café y blanco",
    marks: "Pecho blanco, cejas cafés y una oreja ligeramente doblada",
    description:
      "Luna se perdió durante una tormenta. Es curiosa, juguetona y suele acercarse cuando le ofrecen agua o comida.",
    contactName: "Marcela Vega",
    phone: "+591 70000002",
    email: "marcela.demo@ejemplo.com",
    isUserCreated: false,
  },
  {
    id: "demo-milo",
    name: "Milo",
    photo: "./assets/dogs/milo.jpg",
    status: "Encontrado",
    reportDate: "2026-08-23",
    eventDate: "2026-08-22",
    zone: "Urubó",
    location: "Ingreso a un condominio por el puente del Urubó",
    breed: "Terrier mestizo",
    size: "Pequeño",
    sex: "Macho",
    age: "2 años aprox.",
    color: "Café claro",
    marks: "Orejas grandes, hocico oscuro y no llevaba collar",
    description:
      "Milo fue encontrado caminando solo cerca de la avenida. Está resguardado y se busca a su familia con fotografías o documentación de respaldo.",
    contactName: "Camila Rojas",
    phone: "+591 70000003",
    email: "",
    isUserCreated: false,
  },
  {
    id: "demo-zoe",
    name: "Zoe",
    photo: "./assets/dogs/zoe.jpg",
    status: "Perdido",
    reportDate: "2026-08-22",
    eventDate: "2026-08-21",
    zone: "Las Palmas del Norte",
    location: "Cerca del mercado principal de Las Palmas del Norte",
    breed: "Terrier mestizo",
    size: "Mediano",
    sex: "Hembra",
    age: "5 años",
    color: "Negro y blanco",
    marks: "Franja blanca en el rostro y pecho blanco",
    description:
      "Zoe escapó cuando se abrió la puerta del garaje. Es energética, muy sociable y puede responder a un silbido corto.",
    contactName: "Familia Suárez",
    phone: "+591 70000004",
    email: "",
    isUserCreated: false,
  },
  {
    id: "demo-benny",
    name: "Benny",
    photo: "./assets/dogs/benny.jpg",
    status: "Reunido",
    reportDate: "2026-08-18",
    eventDate: "2026-08-16",
    zone: "Equipetrol",
    location: "Plaza de Equipetrol",
    breed: "Poodle mestizo",
    size: "Pequeño",
    sex: "Macho",
    age: "6 años",
    color: "Crema",
    marks: "Pelaje rizado y placa redonda en el collar",
    description:
      "Benny regresó con su familia gracias a un reporte de la comunidad. Este perfil permanece visible como ejemplo de un caso resuelto.",
    contactName: "Familia Méndez",
    phone: "+591 70000005",
    email: "",
    isUserCreated: false,
  },
];
